Sq 60910 adicionar min e max error no ngx css sq input number
squidit/ngx-css pull request #31
Opened 2023-11-17 19:58 UTC by icaroquadra

2023-11-17 20:24 UTC, dyelmag submitted a review, later dismissed

2023-11-17 21:13 UTC, vinimarcili requested changes
Faltou o bump do package.json e atualizar a documentação com o novo JSON de tradução

2023-11-17 21:13 UTC, vinimarcili commented on application/src/assets/i18n/pt.json
> +    "searchSelectEmpty": "Não há opções a serem selecionadas",
Alterar também no portal e em comunidades, lembra de alterar para as 3 langs

2023-11-17 21:13 UTC, vinimarcili commented on src/components/sq-input-mask/sq-input-mask.component.ts
> +   * The character used as a placeholder for empty positions.
Descrição não fez sentido

2023-11-17 21:13 UTC, vinimarcili commented on src/components/sq-input-mask/sq-input-mask.component.ts
> +  override async setError(key: string, interpolateParams: Object = {}) {
Não entendi esse overwrite se ta igual ao original

2023-11-17 21:13 UTC, vinimarcili commented on src/components/sq-input-mask/sq-input-mask.component.ts
> +  override async change(event: any) {
Não entendi esse overwrite se ta igual ao original

2023-11-17 21:13 UTC, vinimarcili commented on src/components/sq-input-number/sq-input-number.component.ts
> +   * The character used as a placeholder for empty positions.
Melhorar descrição

2023-11-17 21:13 UTC, vinimarcili commented on src/components/sq-input-number/sq-input-number.component.ts
> +   * The character used as a placeholder for empty positions.
Melhorar descrição

2023-11-17 21:13 UTC, vinimarcili commented on src/components/sq-input-number/sq-input-number.component.ts
> +  leftLabelOverwrite: TemplateRef<HTMLElement> | null = null
Arrumas nos projetos onde o ngx-css é usado

2023-11-17 21:13 UTC, vinimarcili commented on src/components/sq-input-number/sq-input-number.component.ts
> +  rightLabelOverwrite: TemplateRef<HTMLElement> | null = null
Arrumas nos projetos onde o ngx-css é usado

2023-11-21 13:33 UTC, icaroquadra commented on src/components/sq-input-mask/sq-input-mask.component.ts
> +  override async change(event: any) {
Realmente não precisava, eu tava fazendo de um jeito burro antes em outro lugar e acabava precisando mas agora no lugar certo nem precisa, tirei fora

2023-11-21 13:33 UTC, icaroquadra commented on src/components/sq-input-number/sq-input-number.component.ts
> +   * The character used as a placeholder for empty positions.
feito

2023-11-21 13:33 UTC, icaroquadra commented on src/components/sq-input-number/sq-input-number.component.ts
> +   * The character used as a placeholder for empty positions.
feito

2023-11-21 13:34 UTC, icaroquadra commented on src/components/sq-input-number/sq-input-number.component.ts
> +  leftLabelOverwrite: TemplateRef<HTMLElement> | null = null
vou abrir o Pr pra alterar as chaves de tradução e já arrumo esses caras também

2023-11-21 13:34 UTC, icaroquadra commented on src/components/sq-input-number/sq-input-number.component.ts
> +  rightLabelOverwrite: TemplateRef<HTMLElement> | null = null
vou abrir o Pr pra alterar as chaves de tradução e já arrumo esses caras também

2023-11-21 16:43 UTC, icaroquadra commented on src/components/sq-input-mask/sq-input-mask.component.html
> -      [showMaskTyped]="showMaskTyped"
voltei o outro

2023-11-21 16:43 UTC, icaroquadra commented on src/components/sq-input-mask/sq-input-mask.component.ts
> +   * The character used as a placeholder for empty positions.
arrumei

2023-11-21 16:43 UTC, icaroquadra commented on src/components/sq-input-mask/sq-input-mask.component.ts
> +   * The character used as a placeholder for empty positions.
arrumei

2023-11-21 16:50 UTC, icaroquadra commented on src/components/sq-input-money/sq-input-money.component.ts
> +  @ContentChild('rightLabelOverwrite')
### [SQ-60972](https://duopana.myjetbrains.com/youtrack/issue/SQ-60972) Atualizar projetos que usam ngx-css com novos parâmetros

será resolvido na tarefa a cima

2023-11-21 20:13 UTC, vinimarcili approved these changes

2023-11-21 20:21 UTC, dyelmag approved these changes

2023-11-21 20:23 UTC, merged