SQ-63319 Migrar os dropdowns pro NGX
squidit/ngx-css pull request #57
Opened 2024-05-09 21:22 UTC by CaioDalo

[SQ-63319](https://duopana.myjetbrains.com/youtrack/issue/SQ-63319/Migrar-os-dropdowns-pro-NGX)

2024-05-09 21:22 UTC, CaioDalo commented
@coderabbitai review

2024-05-10 13:24 UTC, CaioDalo commented on application/src/app/app.component.ts
> +    const html = this.document.getElementsByTagName('html')[0]
This application folder is just a mock to test the components and ensure that the components is working well in ssr

2024-05-10 13:24 UTC, CaioDalo commented on application/src/app/components/header/header.component.ts
> +    const html = this._doc.getElementsByTagName('html')[0]
This application folder is just a mock to test the components and ensure that the components is working well in ssr

2024-05-10 13:31 UTC, CaioDalo commented
@coderabbitai review

2024-05-10 13:47 UTC, JonasPeres submitted a review, later dismissed

2024-05-10 13:53 UTC, CaioDalo commented
@vinimarcili code review

2024-05-10 16:37 UTC, vinimarcili requested changes

2024-05-10 16:37 UTC, vinimarcili commented on application/src/app/app.component.html
> +    <sq-input></sq-input>
volta o anterior aqui

2024-05-10 16:37 UTC, vinimarcili commented on application/src/app/app.component.ts
> +theme = !this.isServer && window.matchMedia('(prefers-color-scheme:dark)').matches ? 'dark' : 'light'
pq precisa do isServer? vc já não ta injetando o window?

2024-05-10 16:37 UTC, vinimarcili commented on application/src/app/components/header/header.component.ts
> +    this.theme = !this.isServer && localStorage.getItem('theme') || this.theme
melhor que botar o isServer é melhor fazer um localStorage?.getItem

2024-05-10 17:41 UTC, JonasPeres submitted a review, later dismissed

2024-05-10 17:44 UTC, vinimarcili approved these changes

2024-05-10 17:50 UTC, vinimarcili approved these changes

2024-05-10 17:51 UTC, merged