Feature/change infinity scroll to cdk virtual scroll on select search and select multi tags
squidit/ngx-css pull request #86
Opened 2024-09-23 12:26 UTC by JoaoBianco

https://duopana.myjetbrains.com/youtrack/issue/SQ-66102/FRONT-Avaliar-Remocao-de-Infinity-Scroll-e-implementacao-do-cdkVirtualScroll-no-sq-select-multi-tags
https://duopana.myjetbrains.com/youtrack/issue/SQ-66101/FRONT-Avaliar-Remocao-de-Infinity-Scroll-e-implementacao-do-cdkVirtualScroll-no-sq-select-search

2024-09-23 12:36 UTC, JoaoBianco commented on src/components/sq-select-multi-tags/sq-select-multi-tags.component.html
> +        </cdk-virtual-scroll-viewport>
In this case, we can use 32px

2024-09-24 12:40 UTC, JonasPeres requested changes
Precisa passar em cada um deles no portal e ver como vai ficar

2024-09-24 12:40 UTC, JonasPeres commented on src/components/sq-select-multi-tags/sq-select-multi-tags.component.scss
> +    height: 305px;
A lista já não tem um tamanho fixo?

2024-09-24 12:40 UTC, JonasPeres commented on src/components/sq-select-search/sq-select-search.component.scss
> +    height: 305px;
Achei que já tinha a altura fixa nos dois

2024-09-24 22:10 UTC, JonasPeres submitted a review, later dismissed

2024-09-25 13:36 UTC, JonasPeres submitted a review, later dismissed

2024-09-25 17:37 UTC, JonasPeres approved these changes

2024-09-26 16:23 UTC, merged